### ISSUE TITLE
HTML report: Function not found 

### ISSUE THREAD

**Issue by brosscle** [tanguyduval/spm12#1]
When I'm trying to run the HTML quality control report module, I always obtain an error like:

> Running job #1
> ------------------------------------------------------------------------
> Running 'HTML report (SCT team)'
> Failed  'HTML report (SCT team)'
> Undefined function 'load_nii_datas' for input arguments of type 'char'.
> In file "/home/cbrossard/Softs/spm12-apps-master/QualityControl/html_report/qc_write.m" (???), function "qc_write" at line 32.
> In file "/home/cbrossard/Softs/spm12-apps-master/QualityControl/cfg_QC.m" (???), function "@(job)qc_write(job.dir,job.inputdate,job.subject,job.nifti,job.mask,job.contrast,job.command,job.slices)" at line 0.
> 
> The following modules did not run:
> Failed: HTML report (SCT team)

It seems that the function load_nii_datas .m is undefined. Indeed, I can't find a so called function.
Did I do something wrong?
Thank you!

**Comment by tanguyduval** [comment]
Thanks for this report. solved in c51fcd08ad3f027781d1bcf29c6d19ce862efd02
Best
